app/models/post.py
from datetime import datetime
from email.policy import default

from ..extensions import db


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    teacher = db.Column(db.Integer, db.ForeignKey('user.id', ondelete='CASCADE'))
    subject = db.Column(db.String(250))
    student = db.Column(db.Integer)
    date = db.Column(db.DateTime, default=datetime.utcnow)

app/models/user.py
from datetime import datetime
from flask_login import UserMixin

from .post import Post
from ..extensions import db, login_manager


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(db.Model, UserMixin):
    id =db.Column(db.Integer, primary_key=True)
    posts = db.relationship(Post, backref='author')
    status = db.Column(db.String(50), default='user')
    name = db.Column(db.String(50))
    login = db.Column(db.String(50))
    password = db.Column(db.String(100))
    date = db.Column(db.DateTime, default=datetime.utcnow())
    avatar = db.Column(db.String(200))

app/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed
from wtforms import StringField, PasswordField, SubmitField, FileField, ValidationError
from wtforms.fields.choices import SelectField
from wtforms.fields.simple import BooleanField
from wtforms.validators import DataRequired, Length, EqualTo

from .models.user import User


class RegistrationForm(FlaskForm):
    name = StringField('ФИО', validators=[DataRequired(), Length(min=2, max=200)])
    login = StringField('Логин', validators=[DataRequired(), Length(min=2, max=20)])
    password = PasswordField('Пароль', validators=[DataRequired(), Length(min=4, max=100)])
    confirm_password = PasswordField('Подтвердите пароль', validators=[DataRequired(), EqualTo('password')])
    avatar = FileField('Загрузите своё фото', validators=[FileAllowed(['jpg', 'jpeg', 'png'])])
    submit = SubmitField('Зарегистрироваться')

    def validate_login(self, login):
        user = User.query.filter_by(login=login.data).first()
        if user:
            raise ValidationError('This login is unawalable!, Enter another.')


class LoginForm(FlaskForm):
    """Form for log in users"""
    login = StringField('Логин', validators=[DataRequired(), Length(min=2, max=20)])
    password = PasswordField('Пароль', validators=[DataRequired(), Length(min=4, max=100)])
    remember = BooleanField("Запомнить меня")
    submit = SubmitField('Войти')


class StudentForm(FlaskForm):
    student = SelectField('student', choices=[], render_kw={'class': 'form-control'})

class TeacherForm(FlaskForm):
    teacher = SelectField('teacher', choices=[], render_kw={'class': 'form-control'})

app/__init__.py
from flask import Flask

from .bundles import register_bundles, bundles
from .config import Config
from .extensions import db, migrate, login_manager, assets
from .routes.user import user
from .routes.post import post


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    app.register_blueprint(user)
    app.register_blueprint(post)

    db.init_app(app)
    migrate.init_app(app, db)
    login_manager.init_app(app)
    assets.init_app(app)

    # LOGIN_MANAGER
    login_manager.login_view = 'user.login'
    login_manager.login_message = 'Вы не можете получить доступ к данной странице. Требуется авторизация.'
    login_manager.login_message_category = 'info'

    # ASSETS
    register_bundles(assets, bundles)

    with app.app_context():
        db.create_all()

    return app

app/routes/post.py
from flask import Blueprint, render_template, request, redirect, abort
from flask_login import login_required, current_user

from ..models.user import User
from ..forms import StudentForm, TeacherForm
from ..extensions import db
from ..models.post import Post

post = Blueprint('post', __name__)

@post.route('/', methods=['GET', 'POST'])
def all():
    form = TeacherForm()
    form.teacher.choices = [t.name for t in User.query.filter_by(status='teacher')]

    if request.method == 'POST':
        teacher = request.form.get('teacher')
        teacher_id = User.query.filter_by(name=teacher).first().id
        posts = Post.query.filter_by(teacher=teacher_id).order_by(Post.date.desc()).all()
    else:
        posts = Post.query.order_by(Post.date.desc()).limit(20).all()
    return render_template('post/all.html', posts=posts, user=User, form=form)

@post.route('/post/create', methods=['POST', 'GET'])
@login_required
def create():
    form = StudentForm()
    form.student.choices = [s.name for s in User.query.filter_by(status='user')]
    if request.method == 'POST':
        subject = request.form.get('subject')
        student = request.form.get('student')
        student_id = User.query.filter_by(name=student).first().id

        post = Post(teacher=current_user.id, subject=subject, student=student_id)

        try:
            db.session.add(post)
            db.session.commit()
            return redirect('/')
        except BaseException as err:
            print(str(err))

    else:
        return render_template('post/create.html', form=form)

@post.route('/post/<int:id>/update', methods=['POST', 'GET'])
@login_required
def update(id):
    post = Post.query.get(id)

    if post.author.id == current_user.id:
        form = StudentForm()
        form.student.data = User.query.filter_by(id=post.student).first().name()
        form.student.choices = [s.name for s in User.query.filter_by(status='user')]
        if request.method == 'POST':
            post.subject = request.form.get('subject')
            student = request.form.get('student')

            post.student = User.query.filter_by(name=student).first().id
            try:
                db.session.commit()
                return redirect('/')
            except BaseException as err:
                print(str(err))

        else:
            return render_template('post/update.html', post=post, form=form)
    else:
        abort(403)

@post.route('/post/<int:id>/delete', methods=['POST', 'GET'])
@login_required
def delete(id):
    post = Post.query.get(id)

    if post.author.id == current_user.id:
        try:
            db.session.delete(post)
            db.session.commit()
            return redirect('/')
        except BaseException as err:
            print(str(err))
            return str(err)
    else:
        abort(403)

app/routes/user.py
from flask import Blueprint, render_template, redirect, flash, url_for, request
from flask_login import login_user, logout_user
from ..functions import save_picture
from ..forms import RegistrationForm, LoginForm
from ..extensions import db, bcrypt
from ..models.user import User


user = Blueprint('user', __name__)


@user.route('/user/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        avatar_filename = save_picture(form.avatar.data)
        user = User(
            name=form.name.data,
            login=form.login.data,
            avatar = avatar_filename,
            password = hashed_password
        )
        try:
            db.session.add(user)
            db.session.commit()
            flash(f'Conratulations! {user.name} registered!', 'Success!!!')
            return redirect(url_for('user.login'))
        except Exception as err:
            print(str(err))
            flash(f'При регистрации произошла ошибка!', 'danger')
    return render_template('user/register.html', form=form)

@user.route('/user/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(login=form.login.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('post.all'))
        else:
            flash('Ошибка входа! Пожалуйста проверьте Логин и Пароль.', 'danger')
    return render_template('user/login.html', form=form)

@user.route('/user/logout', methods=['GET', 'POST'])
def logout():
    logout_user()
    return redirect(url_for('post.all'))

app/templates/main/_flash.html
<!-- FLASH MESSAGES -->
{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category, message in messages %}
            <div class="alert alert-{{ category }}">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
{% endwith %}
<!-- FLASH MESSAGES -->

app/templates/main/_footer.html
<div class="col-md-4 d-flex align-items-center">
  <a href="/" class="mb-3 me-2 mb-md-0 text-decoration-none lh-1">
    <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
  </a>
  <span class="mb-3 mb-md-0">© 2024 Company, Inc</span>
</div>

<ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
  <li class="ms-3"><a class="" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"></use></svg></a></li>
  <li class="ms-3"><a class="" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"></use></svg></a></li>
  <li class="ms-3"><a class="" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#facebook"></use></svg></a></li>
</ul>

app/templates/main/_header.html
<!--<header class="p-3 text-bg-dark">-->
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="{{ url_for('post.all') }}" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
<!--          <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>-->
          <img class="header__img" src="{{ url_for('static', filename='img/Pngtree_spa_logo_7902878.png') }}" alt="health">
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href="{{ url_for('post.all') }}" class="nav-link px-2 text-secondary">Home</a></li>
          <li><a href="#" class="nav-link px-2 text-white">Features</a></li>
          <li><a href="#" class="nav-link px-2 text-white">Pricing</a></li>
          <li><a href="#" class="nav-link px-2 text-white">FAQs</a></li>
          <li><a href="#" class="nav-link px-2 text-white">About</a></li>
          {% if current_user.is_authenticated and current_user.status == 'teacher' %}
            <li><a href="{{ url_for('post.create') }}" class="nav-link px-2 text-white">Добавить тему</a></li>
          {% endif %}
        </ul>


        <div class="text-end">
            {% if current_user.is_authenticated %}
                <span>{{ current_user.login }} </span>
                <a href = "{{ url_for('user.logout') }}" class="btn btn-outline-light me-2">Выйти</a>
            {% else %}

                <a href = "{{ url_for('user.login') }}" class="btn btn-outline-light me-2">Войти</a>
                <a href = "{{ url_for('user.register') }}" class="btn btn-warning">Зарегистрироваться</a>
            {% endif %}
        </div>
      </div>
    </div>
<!--  </header>-->

app/templates/main/base.html
<!DOCKTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/libs/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    {% block style %}{% endblock %}
    <title>
        {% block title %}{% endblock %}
    </title>
</head>
<body>

<div class="page">
    <header class="p-3 text-bg-dark">{% include 'main/_header.html' %}</header>

    <main class="content">
        {% include 'main/_flash.html' %}
            <h1>{{ self.title() }}</h1>
        {% block content %}{% endblock %}
    </main>
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">{% include 'main/_footer.html' %}</footer>
</div>

    <script src="{{ url_for('static', filename='js/libs/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/app.js') }}"></script>
{% block script %}{% endblock %}
</body>
</html>

app/templates/post/all.html
{% extends 'main/base.html' %}

{% block title %}All themes{% endblock %}

{% block style %}
    {% assets 'post_all_css' %}
        <link rel="stylesheet" href="{{ ASSET_URL }}">
    {% endassets %}
{% endblock %}

{% block content %}

<form method="post" class="form-control d-flex flex-row gap-2" id="teacherForm">
    {{ form.csrf_token }}
    {{ form.teacher }}
    <input type="submit" class="btn btn-success" value="Показать">
</form>
<div class="table-responsive custom-table-responsive">
    <table class="table custom-table">
        <thead>
            <tr>
                <th scope="col">Teacher</th>
                <th scope="col">Subject</th>
                <th scope="col">Student</th>
                {% if current_user.is_authenticated %}
                    <th scope="col">Action</th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
            {% for post in posts %}
            <tr scope="row">
                <td>
                    <img width="76px" height="76px" src="{{ url_for('static', filename='upload/'+post.author.avatar) }}" alt="Преподаватель">
                    {{ post.author.name }}
                </td>
                <td>{{ post.subject }}</td>
                <td>
                    {% with student = user.query.get(post.student) %}
                        <img width="76px" height="76px" src="{{ url_for('static', filename='upload/'+student.avatar) }}" alt="Студент">
                        {{ student.name }}
                    {% endwith %}
                </td>
                <td>
                    {% if current_user.is_authenticated and post.author.id == current_user.id %}
                        <a href="{{ url_for('post.update', id=post.id) }}" class="btn btn-sm btn-secondary"><span class="fa fa-edit"></span></a>
                        <a href="{{ url_for('post.delete', id=post.id) }}" class="btn btn-sm btn-danger"><span class="fa fa-trash"></span></a>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

{% block script %}
    {% assets 'post_all_js' %}
        <script type="text/javascript" src="{{ ASSET_URL }}"></script>
    {% endassets %}
{% endblock %}

app/templates/post/create.html
{% extends 'main/base.html' %}

{% block title %}Добавление темы{% endblock %}
{% block content %}
<form method="post" class="form-control d-flex flex-column gap-2">
    <input name="subject" type="text" placeholder="Тема: " class="form-control">
    {{ form.student }}
    <input value="Добавить" type="submit" class="btn btn-success">
</form>
{% endblock %}

app/templates/post/update.html
{% extends 'main/base.html' %}

{% block title %}Редактирование темы "{{ post.subject }}"{% endblock %}

{% block content %}
<form method="post" class="form-control d-flex flex-column gap-2">
    <input value="{{ post.subject }}" name="subject" type="text" placeholder="Тема: " class="form-control">
    {{ form.student }}
    <input value="Обновить" type="submit" class="btn btn-success">
</form>
{% endblock %}

app/templates/user/login.html
{% extends 'main/base.html' %}

{% block title %}Authorisation{% endblock %}

{% block content %}
    <form method="post" class="form-control d-flex flex-column gap-2">
        {{ form.csrf_token }}
        {{ form.login(class="form-control", placeholder="Логин") }}
        {{ form.password(class="form-control", placeholder="Пароль") }}
        <div class="d-flex flex-row justify-content-center gap-2">
            {{ form.remember.label }}{{ form.remember(class="form-check") }}
        </div>

        {{ form.submit(class="btn btn-success") }}
    </form>
{% endblock %}

app/templates/user/register.html
{% extends 'main/base.html' %}

{% block title %}User registration{% endblock %}

{% block content %}
    <form method="post" enctype="multipart/form-data" class="form-control d-flex flex-column gap-2">
        {{ form.csrf_token }}
        {{ form.name(class="form-control", placeholder="ФИО") }}
        {{ form.login(class="form-control", placeholder="Логин") }}
        {% if form.login.errors %}
            <div class="invalid-feedback" style="display: block!important;">
                {% for error in form.login.errors %}
                    <span>
                        {{ error }}
                    </span>
                {% endfor %}
            </div>
        {% endif %}
        {{ form.avatar(class="form-control") }}
        {{ form.password(class="form-control", placeholder="Пароль") }}
        {{ form.confirm_password(class="form-control", placeholder="Подтверждите пароль") }}
        {{ form.submit(class="btn btn-success") }}
    </form>
{% endblock %}